default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: blog_rails6_dev


test:
  <<: *default
  database: blog_rails6_test


production:
  <<: *default
  database: blog_rails6
